language: minimal
sudo: false

branches:
  only:
  - master
  - /feature\/.*/

notifications:
  email: false

git:
  depth: 1

env:
  global:
    - TERRAFORM_VERSION=0.11.10
    - SOURCE_PATH=ecs_travis

# Install Terraform executable
install:
  - wget https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip
  - unzip terraform_${TERRAFORM_VERSION}_linux_amd64.zip -d /opt/terraform
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
  - rm -f terraform.zip

# Plan
script:
  - cd ${SOURCE_PATH}
  - terraform init -backend-config="config/eu-central-1/config.remote"
  - terraform plan -var-file="config/eu-central-1/config.tfvars" -out=terraform.tfplan

# Apply
deploy:
- provider: script
  script: 
    - terraform apply -var-file="config/eu-central-1/config.tfvars" terraform.tfplan
  skip_cleanup: true
  on:
    branch: master
