language: minimal
sudo: false

branches:
  only:
  - master
  - /feature\/.*/

notifications:
  email: false

git:
  depth: 1

matrix:
  include:
    - name: "00_bootstrap eu-central-1"
      env: SOURCE_PATH=00_bootstrap
    - name: "01_ec2 eu-central-1"
      env: SOURCE_PATH=01_ec2

# Install Terraform executable
install:
  - wget https://releases.hashicorp.com/terraform/0.11.10/terraform_0.11.10_linux_amd64.zip
  - unzip terraform_0.11.10_linux_amd64.zip -d /opt/terraform
  - sudo ln -s /opt/terraform/terraform /usr/bin/terraform
  - rm -f terraform.zip

# Plan
script:
  - cd ${SOURCE_PATH}
  - terraform init
  - terraform plan -out=terraform.tfplan

# Apply
deploy:
- provider: script
  script: 
    - terraform apply terraform.tfplan
  skip_cleanup: true
  on:
    branch: master